services:
  innogram-frontend:
    build: .
    container_name: innogram-frontend-container

    ports:
      - '3500:3500'
    env_file:
      - './.env.local'
    networks:
      - innogram-net
    restart: unless-stopped

networks:
  innogram-net:
    external: true